### ISSUE TITLE
Restrict signup for UC emails

### ISSUE THREAD

**Issue by Uzval-Mallepeddi** [uclibs/application_portfolio#126]
- People only with UC email (@uc.edu, @mail.uc.edu, @ucmail.uc.edu) can signup. (No gmail, hotmail, comcast, e.t.c allowed)

**Comment by Uzval-Mallepeddi** [comment]
@hortongn Perfect. Sounds like a plan.

**Comment by hortongn** [comment]
I think we can get by without recaptcha on the signup page since it is limited to on-campus only.  We can add it later if we have problems.

However, what it might be nice to send an email to uclappdev@uc.edu whenever someone signs up.  That will alert us that a new user is on the system.  IF we don't recognize the email we can take action.  Thoughts? @scherztc @Uzval-Mallepeddi

**Comment by Uzval-Mallepeddi** [comment]
@hortongn It makes perfect sense to me.

**Comment by scherztc** [comment]
@hortongn Works for me.
