### ISSUE TITLE
Need more fields on Software Records List

### ISSUE THREAD

**Issue by scherztc** [uclibs/application_portfolio#80]
The Software Records Display List needs to include more fields.

The following fields should be added:

**Comment by scherztc** [comment]
Sortable

**Comment by scherztc** [comment]
@Uzval-Mallepeddi 
name, vendor, description, date_implmented, software_type, url, Actions

**Comment by Uzval-Mallepeddi** [comment]
@scherztc 
Thomas, From my perspective, having "description" in the table would lead to a bad design. Because, there might be users who enter short lines of description and some others fill in big lines of text in the description. Having long lines as description would increase the size of size which leads to unfamiliar table design.

If a user/admin/manager/owner want to have a look at the "description", wouldn't it make sense if he enters the record individually and checkout the description ?

Need your inputs :)

**Comment by scherztc** [comment]
Good points.  Strike description from the display.
